#if !defined (__SAIOBJECT_TYPE_EXT_H_)
#define __SAIOBJECT_TYPE_EXT_H_


SAI_OBJECT_TYPE_TABLE_PEERING_ENTRY = SAI_OBJECT_TYPE_MAX  + 1,
SAI_OBJECT_TYPE_TABLE_VHOST_ENTRY =  SAI_OBJECT_TYPE_MAX + 2,
SAI_OBJECT_TYPE_EXT_MAX = SAI_OBJECT_TYPE_MAX + 3,
#define SAI_OBJECT_TYPE_MAX  SAI_OBJECT_TYPE_EXT_MAX  

#endif /** __SAIOBJECT_TYPE_EXT_H_ */
